/**
 * Speaker Notes Export
 * Returns a clean text file with all speaker notes.
 */
import { NextRequest, NextResponse } from "next/server";
import type { Slide } from "@/types";

export async function POST(request: NextRequest) {
  try {
    const { slides, title } = (await request.json()) as {
      slides: Slide[];
      title: string;
    };

    if (!slides || !Array.isArray(slides) || slides.length === 0) {
      return NextResponse.json(
        { error: "No slides provided." },
        { status: 400 }
      );
    }

    const presentationTitle = title || "Presentation";
    let text = "";
    text += `${"=".repeat(60)}\n`;
    text += `  SPEAKER NOTES: ${presentationTitle}\n`;
    text += `  Generated by Aryvora AI\n`;
    text += `${"=".repeat(60)}\n\n`;

    slides.forEach((s, i) => {
      text += `${"─".repeat(50)}\n`;
      text += `SLIDE ${i + 1} of ${slides.length}: ${s.heading}\n`;
      text += `Type: ${s.type}\n`;
      text += `${"─".repeat(50)}\n`;

      if (s.notes) {
        text += `${s.notes}\n\n`;
      } else {
        // Auto-generate basic notes from slide content
        text += `[Auto-generated talking points]\n`;
        if (s.bullets && s.bullets.length > 0) {
          s.bullets.forEach((b, j) => {
            text += `  ${j + 1}. ${b}\n`;
          });
        }
        if (s.sub) {
          text += `  Note: ${s.sub}\n`;
        }
        text += "\n";
      }
    });

    text += `${"=".repeat(60)}\n`;
    text += `  End of Speaker Notes\n`;
    text += `${"=".repeat(60)}\n`;

    const safeTitle = presentationTitle
      .replace(/[^a-zA-Z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .slice(0, 50);

    return new NextResponse(text, {
      status: 200,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="${safeTitle}-speaker-notes.txt"`,
      },
    });
  } catch (err) {
    console.error("Speaker notes export error:", err);
    return NextResponse.json(
      {
        error:
          err instanceof Error
            ? `Export failed: ${err.message}`
            : "Failed to export speaker notes. Please try again.",
      },
      { status: 500 }
    );
  }
}
